# Generated by Django 3.2.25 on 2024-08-08 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(max_length=255)),
                ('result', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(blank=True, max_length=50, null=True)),
                ('dark_mode', models.BooleanField(blank=True, null=True)),
                ('high_contrast_mode', models.BooleanField(blank=True, null=True)),
                ('text_to_speech', models.BooleanField(blank=True, null=True)),
                ('speech_to_text', models.BooleanField(blank=True, null=True)),
                ('font_size', models.IntegerField(blank=True, null=True)),
                ('color_blind_mode', models.BooleanField(blank=True, null=True)),
                ('keyboard_navigation', models.BooleanField(blank=True, null=True)),
                ('vibration_feedback', models.BooleanField(blank=True, null=True)),
                ('sound_feedback', models.BooleanField(blank=True, null=True)),
                ('language', models.CharField(blank=True, max_length=50, null=True)),
                ('custom_precision', models.IntegerField(blank=True, null=True)),
                ('custom_formulas', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userpreference_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SecuritySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('two_factor_authentication', models.BooleanField(blank=True, null=True)),
                ('biometric_authentication', models.BooleanField(blank=True, null=True)),
                ('data_anonymization', models.BooleanField(blank=True, null=True)),
                ('privacy_settings', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='securitysetting_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CloudSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloud_storage_enabled', models.BooleanField(blank=True, null=True)),
                ('real_time_updates', models.BooleanField(blank=True, null=True)),
                ('collaborative_mode', models.BooleanField(blank=True, null=True)),
                ('cross_device_sync', models.BooleanField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cloudsetting_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
